### ISSUE TITLE
게시글 삭제 기능을 구현한다.

### ISSUE THREAD

**Issue by hectick** [woowacourse-teams/2023-edonymyeon#12]
## 📝 요약
게시글 삭제 요청이 들어오면 게시글을 삭제하는 기능을 구현합니다.

## 💡 Todo
- [x] 게시글 삭제 api 구현
- [x] 데이터베이스에서 물리적 삭제되도록 구현
- [x] 테스트 코드 구현
