### ISSUE TITLE
내가 쓴 글 조회 페이지

### ISSUE THREAD

**Issue by Choisehyeon** [woowacourse-teams/2023-edonymyeon#125]
## 📝 요약
내가 쓴 글 조회 페이지를 구현한다.

## 💡 Todo
Android(로피)
- [x] #128
  - [x] 소비확정 버튼을 누르면 소비 금액을 입력받는 다이얼로그가 열린다.
  - [x] 다이얼로그에 소비금액을 입력할 수 있다.
- [x] #129
   - [x] 소비 확정인 경우 금액까지 보여준다.
   - [x] 소비확정이나 절약확정 버튼을 누르고 나면, 확정 취소 버튼으로 바뀐다.

backend(호이, 이리내)
- [x] #130
    - [x] 소비 금액을 입력받아 소비확정하는 기능을 구현한다.
    - [x] 절약확정 기능을 구현한다.
- [x] #131
- [x] #123 

Common
- [x] 내가 쓴 글이 최신순으로 서버에서 가져온다. 
- [x] 소비확정을 누른 후 금액을 입력하고 확인을 누르면 서버에 전송한다.
## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
