### ISSUE TITLE
소비확정인지 절약확정인지 알려준다.

### ISSUE THREAD

**Issue by Choisehyeon** [woowacourse-teams/2023-edonymyeon#129]
## 📝 요약
소비 확정인지 절약 확정인지 알려준다.

## 💡 Todo
- [x] 소비 확정인지 절약 확정인지 알려준다.
  - [x] 소비 확정인 경우 금액까지 보여준다.
  - [x] 소비확정이나 절약확정 버튼을 누르고 나면, 확정 취소 버튼으로 바뀐다.

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
