### ISSUE TITLE
마이페이지 디자인 전반적으로 수정된 부분 적용

### ISSUE THREAD

**Issue by sujin9** [woowacourse-teams/2023-edonymyeon#136]
## 📝 요약
마이 페이지 디자인 변경 사항들을 적용한다.

## 💡 Todo
- [X] 중간 삭제된 아이템들 지우기
- [x] 하단 내가 쓴 글 추가하고 여백 조정하기
- [x] 문구 수정하기
- [x] 닉네임 하단 금액 출력하기 (default: 0원)
- [x] 로그인 버튼 추가하기 (visible 추후 조정)

## 🔗 관련 링크
<img src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/8490058/ab434e9d-1bc3-42ca-8ef6-440ac4d66fa1" width=180 />
