### ISSUE TITLE
마이페이지 - 로그인이 되어 있을 때 화면 구성 및 API 연동

### ISSUE THREAD

**Issue by sujin9** [woowacourse-teams/2023-edonymyeon#138]
## 📝 요약
마이 페이지에서 로그인이 되어 있을 때 화면을 구현한다.

## 💡 Todo
- [x] 사용자 관련 - 닉네임, 프로필 이미지: API 연동
- [x] 절약/소비금액 관련 - 이번 달 절약 금액, 소비 금액 API 연동
- [x] 절약/소비금액 관련 - 6달 절약 금액, 소비 금액 그래프 API 연동

## 🔗 관련 링크
<img src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/8490058/ab434e9d-1bc3-42ca-8ef6-440ac4d66fa1" width=180 />
