### ISSUE TITLE
게시글 상세 페이지 뷰 및 추천/비추천 기능 구현

### ISSUE THREAD

**Issue by sujin9** [woowacourse-teams/2023-edonymyeon#17]
## 📝 요약
게시글 상세 페이지 뷰를 구현하고,
게시글 내용을 불러오는 기능과 추천/비추천 기능을 ViewModel과 Livedata를 이용하여 구현한다.

## 💡 Todo
- [x] 게시글 관련 정보들이 표시된다
- [x] 추천, 비추천 아이콘 및 비율(프로그레스바)이 표시된다
- [x] 추천, 비추천 기능을 수행할 수 있다
- [x] 앱 바를 구현한다.
- [x] 스크랩 버튼이 보인다. (추후 기능 구현)
