### ISSUE TITLE
게시글 작성/수정 페이지

### ISSUE THREAD

**Issue by sujin9** [woowacourse-teams/2023-edonymyeon#18]
## 📝 요약
게시글을 작성 및 수정하는 페이지를 구현한다

## 💡 Todo
- [X] 앱바 초기세팅을 구현한다
- [x] 제목, 가격, 게시글 내용을 입력받는다
- [x] 작성/수정 페이지 뷰 구현한다
    - [x] 카테고리 선택 스피너를 보여준다 (추후 기능 구현)
- [x] 이미지를 첨부할 수 있다 (이미지 개수 제한: 최대 10개)
    - [x] 카메라로 촬영
    - [x] 갤러리에서 선택
    - [x] 첨부한 이미지는 하단 가로 리사이클러뷰로 볼 수 있다
    - [x] 첨부한 이미지 각각은 X버튼을 눌러 삭제할 수 있다

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
