### ISSUE TITLE
마이 페이지 (프래그먼트) 뷰 구현

### ISSUE THREAD

**Issue by sujin9** [woowacourse-teams/2023-edonymyeon#19]
## 📝 요약
마이 페이지를 프래그먼트로 구현한다

## 💡 Todo
- [x] 내 정보 (프로필 사진, 닉네임)가 표시된다
- [x] 피그마 파일을 따라 뷰를 그린다
- [ ] 내가 쓴 글 클릭 시, 내가 쓴 글 목록 페이지로 이동한다
