### ISSUE TITLE
핫 게시글 뷰를 구현한다.

### ISSUE THREAD

**Issue by Choisehyeon** [woowacourse-teams/2023-edonymyeon#227]
## 📝 요약
핫 게시글 뷰를 구현한다.

## 💡 Todo
- [x] 리사이클러뷰로 구현한다(가로)
- [x] 리사이클러뷰 아이템을 만든다.
- [x] 아이템 선택시 상세페이지로 이동한다.

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
