### ISSUE TITLE
화면 간 Intent를 연결한다

### ISSUE THREAD

**Issue by rhkrwngud445** [woowacourse-teams/2023-edonymyeon#35]
## 📝 요약
화면 간 Intent를 연결한다

## 💡 Todo
- [x] 화면 간 이동을 구현한다
- [x] 팩토리 함수를 이용하여 해당 액티비티 인탠트를 만들 수 있다
- [x] 화면 간 이동 시 데이터를 전달한다
