### ISSUE TITLE
알림 설정기능을 구현한다.

### ISSUE THREAD

**Issue by rhkrwngud445** [woowacourse-teams/2023-edonymyeon#353]
## 📝 요약
알림 기능을 최종 구현 및 보완한다.

## 💡 Todo
- [x] 알림 설정 기능
- [ ] 홈화면 알림 표시 색상 변경 (이미지 대신 badge로 사용)
- [x] 알림을 통한 조회 시, notiication query 조회
- [ ] 알림 목록 페이지에서 읽음, 안읽음 여부 구분
- [x] 로그인시 token 보내고 있는지 체크

## 🔗 관련 링크
아 즐겁다
