### ISSUE TITLE
댓글 작성, 삭제 기능을 구현한다.

### ISSUE THREAD

**Issue by hectick** [woowacourse-teams/2023-edonymyeon#355]
## 📝 요약
댓글 작성과 삭제 기능을 구현합니다.

## 💡 Todo
- [x] 댓글 작성시에는 본문과, 사진을 첨부할 수 있습니다.
    - [x] 사진은 0개 또는 1개 가능합니다.
- [x] 댓글 삭제는 soft delete로 구현합니다.
