### ISSUE TITLE
게시글 작성/수정 페이지 - 서버 연결

### ISSUE THREAD

**Issue by Choisehyeon** [woowacourse-teams/2023-edonymyeon#36]
## 📝 요약
기능 요청에 대한 간략한 설명을 작성해주세요.

## 💡 Todo
- [x] 게시글을 등록하면 서버에 게시글이 보내진다
- [x] 이미지 multipart 사용해서 서버에 보낸다
- [x] 등록 버튼을 누르면 게시글 상세페이지로 이동한다

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
