### ISSUE TITLE
게시글 조회관련 api들에 댓글 수를 반영하고, 스크랩 수를 제거한다.

### ISSUE THREAD

**Issue by hectick** [woowacourse-teams/2023-edonymyeon#375]
## 📝 요약
게시글 상세 조회, 게시글 전체조회, 핫게시글 조회, 검색 결과 응답 형태에 댓글 수 반영 및 스크랩 수 제거

## 💡 Todo
- [x] ReactionCountResponse에서 scrapCount 제거
- [x] 게시글 상세 조회 api에서 isScrap 제거
- [x] commentCount 기존에 0으로 들어가던 것을 수정
    - [x] 핫 게시글 조회
    - [x] 게시글 전체 조회
    - [x] 게시글 상세 조회
    - [x] 게시글 검색
