### ISSUE TITLE
게시글 상세 페이지 - 로그인 여부에 따른 화면 변화 및 이벤트 추가

### ISSUE THREAD

**Issue by sujin9** [woowacourse-teams/2023-edonymyeon#47]
## 📝 요약
앱 바의 메뉴 버튼은 작성자 본인인 경우에만 보이며, 클릭 시 수정/삭제 이벤트를 합니다.

## 💡 Todo
- [x] 작성자 본인인 경우에만 앱 바 > 메뉴의 수정/삭제 항목이 보인다.
    - [x] 삭제를 클릭하면 삭제 여부를 묻는 커스텀 다이얼로그가 보인다.
- [x] 작성자 본인인 경우 스크랩 할 수 없다.
- [x] 스크랩을 하면 스크랩수가 증가한다
- [ ] 앱 바 > 백 버튼을 클릭하면 뒤로 이동한다.
