### ISSUE TITLE
게시글 작성/수정 페이지 - 추가 기능 구현

### ISSUE THREAD

**Issue by Choisehyeon** [woowacourse-teams/2023-edonymyeon#50]
## 📝 요약
게시글 작성/수정 페이지의 일부 추가 기능을 구현한다.

## 💡 Todo
- [x] 제목이 입력되지 않은 경우 작성할 수 없다
- [x] 이전 페이지로부터 작성/수정 여부를 가져온다
- [x] 앱 바 등록 버튼이 동작된다

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
