### ISSUE TITLE
게시글 상세 조회시, 해당 게시글에 대한 추천/비추천 수와 추천/비추천 여부를 읽어온다

### ISSUE THREAD

**Issue by jyeost** [woowacourse-teams/2023-edonymyeon#58]
## 📝 요약
게시글 상세 조회시, 해당 게시글에 대한 추천/비추천 수와 추천/비추천 여부를 읽어온다

## 💡 Todo
- [x] 게시글 조회시 해당 하는 추천/비추천 목록을 전부 가져온다
- [x] 추천과 비추천의 개수를 센다
- [x] 해당 게시글에 로그인 한 사람의 추천/ 비추천 여부를 읽어온다.
